# config.yaml
symbol: EURUSD
lookback_window: 50
features:
  - Open
  - High
  - Low
  - Close
  - Volume
  - Sentiment
initial_balance: 10000
commission: 0.0002
lstm_hidden: 64
timeframe: M1  # format: MT5 timeframe key
lot_size: 0.1
slippage: 5
simulate: true
risk_percent: 0.02       # Procent kapitału na jedno ryzyko
max_drawdown: 0.10      # Maksymalny dozwolony drawdown (10%)
n_envs: 1               # Liczba równoległych environmentów dla wektorization
